### PR TITLE
Issue 144 stop search

### PR DESCRIPTION
**Pull request by CachingFoX**
A bug fix for issue #144 

The while loop will be stopped if there no table rows elements in loaded results

### CODE REVIEW

**Comment by CachingFoX** [comment]
I check the Travis CI reports: builds for Python 3.5 and 3.7 run fine, but with Python 3.6 the build raise an exception. I don't understand why?

**Comment by FriedrichFroebel** [comment]
Wouldn't be `if not geocaches_table.find_all("tr"))` enough? And we might should save `geocaches_table.find_all("tr")` in an own variable before and use it in line 254 as well to reduce duplicate code.

**Comment by CachingFoX** [comment]
> Wouldn't be `if not geocaches_table.find_all("tr"))` enough? 
Yes it could! I changed this.
> And we might should save `geocaches_table.find_all("tr")` in an own variable before and use it in line 254 as well to reduce duplicate code.
I did it :-) and push the update to Github.

Please can you check my PR, again?

**Comment by FriedrichFroebel** [comment]
I added a new issue for the failing test as it seems to be unrelated to this PR, so this is ready to be merged.

**Pull request merged**
