### PR TITLE
Error Handling

### PR DESCRIPTION
**Pull request by jdownie**
While writing a script for my Magellan Explorist GC I fixed a few errors. Hope they fit with the rest of your great work!

### CODE REVIEW

**Comment by jdownie** [comment]
I tried tom resolve all of the errors that Travis CI found, but the last one was a login issue. Anyway. Hope I can help more in the future. Thanks again!

**Comment by tomasbedrich** [comment]
Hello James, thanks for your pull request! But before I look at the changes you made, please fix the location of `cache.py` – you probably pushed it to wrong directory.

**Comment by jdownie** [comment]
I've taken a look and i'm not sure what i've done wrong. I forked
https://github.com/tomasbedrich/pycaching to
https://github.com/jdownie/pycaching, and the changes that I made were to
cache.py in the "pycaching" folder within that repo. That's okay isnt it?

James



James Downie
0408 349 066
jdownie@gmail.com

**Comment by jdownie** [comment]
Better now?

**Comment by jdownie** [comment]
I've pushed in a fixed copy but i'm not sure if I need to raise a new pull
request or not. Sorry i'm making a mess of this.


James Downie
0408 349 066
jdownie@gmail.com

**Comment by tomasbedrich** [comment]
Definitely better! I will review it soon.

**Comment by jarhill0** [comment]
Just re-open this one.

**Comment by jdownie** [comment]
Oh, you've re-opened this one. I shouldn't have closed it. I didn't realise that subsequent commits would be include in a pull request.

**Comment by tomasbedrich** [comment]
I have tested your work on following caches: GC18WF8, GC1GW54, GC2WXPN, GC1PAR2 and I think we should update parsing of more fields, than only `type` and `note`. Besides that, I think that `note` can be parsed from the 8th index, not the 7th.

This works for me:

```diff
diff --git a/pycaching/cache.py b/pycaching/cache.py
index 1f5d06a..78eb191 100644
--- a/pycaching/cache.py
+++ b/pycaching/cache.py
@@ -952,16 +952,16 @@ class Waypoint(object):
             waypoints_table = waypoints_table.find_all("tr")
             for r1, r2 in zip(waypoints_table[1::2], waypoints_table[2::2]):
                 columns = r1.find_all("td") + r2.find_all("td")
-                identifier = columns[4].text.strip()
-                type = columns[2].find("img").get("title")
-                location_string = columns[6].text.strip()
+                identifier = columns[3].text.strip()
+                type = columns[1].find("img").get("title")
+                location_string = columns[5].text.strip()
                 try:
                     loc = Point(location_string)
                 except ValueError:
                     loc = None
                     logging.debug("No valid location format in waypoint {}: {}".format(
                         identifier, location_string))
-                note = columns[10].text.strip()
+                note = columns[8].text.strip()
                 waypoints_dict[identifier] = cls(identifier, type, loc, note)
         return waypoints_dict
```

Can you please verify it and possibly update your pull request? Also it would be nice to squash all the unused commits.

If want to help with some new feature as well, you can try to add parsing of waypoint name. ;) It should be simple – but preferably create a separate PR so we can merge this bugfix ASAP.

**Pull request closed without merging**
